const products=[
 {id:1,name:'The Aster Lounge Chair',type:'Lounge',space:['Garden','Patio','Poolside'],price:12800,image:'https://images.unsplash.com/photo-1598301257982-0cf014dabbcd?auto=format&fit=crop&w=800&q=85',badge:'NEW'},
 {id:2,name:'The Noura Dining Chair',type:'Dining',space:['Garden','Patio','Dining'],price:6950,image:'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=800&q=85',badge:'BESTSELLER'},
 {id:3,name:'The Sienna Folding Chair',type:'Folding',space:['Balcony','Terrace','Garden'],price:4750,image:'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=85',badge:''},
 {id:4,name:'The Marea Armchair',type:'Lounge',space:['Poolside','Patio','Garden'],price:11200,image:'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=85',badge:'LIMITED'},
 {id:5,name:'The Amani Dining Chair',type:'Dining',space:['Balcony','Dining'],price:7400,image:'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&q=85',badge:''},
 {id:6,name:'The Riva Folding Chair',type:'Folding',space:['Terrace','Balcony'],price:5200,image:'https://images.unsplash.com/photo-1617104551722-3b2d513664c8?auto=format&fit=crop&w=800&q=85',badge:''}
];let activeSpace='Garden',activeFilter='All',cart=[],wishlist=[];
const money=n=>'EGP '+n.toLocaleString('en-US');
function renderProducts(){const showing=products.filter(p=>(activeFilter==='All'||p.type===activeFilter)&&(activeSpace==='All'||p.space.includes(activeSpace)));document.querySelector('#products').innerHTML=showing.length?showing.map(p=>`<article class="product"><div class="product-image"><img src="${p.image}" alt="${p.name}"></div>${p.badge?`<span class="badge">${p.badge}</span>`:''}<button class="wish ${wishlist.includes(p.id)?'selected':''}" data-wish="${p.id}" aria-label="Add ${p.name} to wishlist">${wishlist.includes(p.id)?'♥':'♡'}</button><div class="product-meta"><h3>${p.name}</h3><p>Solid teak · Made for outdoors</p><div class="product-bottom"><span class="price">${money(p.price)}</span><button class="add" data-add="${p.id}">Add to bag</button></div></div></article>`).join(''):'<p>No pieces match these choices yet.</p>';}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function renderCart(){document.querySelector('#cartCount').textContent=cart.length;document.querySelector('#subtotal').textContent=money(cart.reduce((t,p)=>t+p.price,0));document.querySelector('#cartItems').innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-line"><img src="${p.image}" alt=""><div><h4>${p.name}</h4><p>Solid teak · Quantity 1</p><b>${money(p.price)}</b></div><button class="remove" data-remove="${i}">Remove</button></div>`).join(''):'<p class="empty">Your bag is ready for something beautiful.</p>';}
document.addEventListener('click',e=>{let id=Number(e.target.dataset.add||e.target.dataset.wish);if(e.target.dataset.add){cart.push(products.find(p=>p.id===id));renderCart();toast('Added to your bag.');}if(e.target.dataset.wish){wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];document.querySelector('#wishCount').textContent=wishlist.length;renderProducts();toast(wishlist.includes(id)?'Saved to your wishlist.':'Removed from wishlist.');}if(e.target.dataset.remove){cart.splice(Number(e.target.dataset.remove),1);renderCart()}if(e.target.classList.contains('filter')){activeFilter=e.target.dataset.filter;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b===e.target));renderProducts()}if(e.target.closest('.space-card')){const b=e.target.closest('.space-card');activeSpace=b.dataset.space;document.querySelectorAll('.space-card').forEach(x=>x.classList.toggle('active',x===b));document.querySelector('#filterNote').textContent='Curated for '+activeSpace;renderProducts();document.querySelector('#collection').scrollIntoView({behavior:'smooth'})}});
document.querySelector('#showAll').onclick=()=>{activeSpace='All';activeFilter='All';document.querySelectorAll('.filter').forEach((b,i)=>b.classList.toggle('active',i===0));document.querySelector('#filterNote').textContent='All outdoor spaces';renderProducts()};
const drawer=document.querySelector('#drawer'),overlay=document.querySelector('#overlay');document.querySelector('#cartButton').onclick=()=>{drawer.classList.add('open');overlay.classList.add('show')};document.querySelector('.drawer .close').onclick=()=>{drawer.classList.remove('open');overlay.classList.remove('show')};overlay.onclick=()=>{drawer.classList.remove('open');overlay.classList.remove('show')};
const dialog=document.querySelector('#checkoutDialog');document.querySelector('#checkout').onclick=()=>{if(!cart.length)return toast('Your bag is still empty.');drawer.classList.remove('open');overlay.classList.remove('show');dialog.showModal()};document.querySelector('.modal-close').onclick=()=>dialog.close();document.querySelector('#checkoutForm').onsubmit=e=>{e.preventDefault();cart=[];renderCart();dialog.close();toast('Thank you — your order is confirmed.');};document.querySelector('#subscribeForm').onsubmit=e=>{e.preventDefault();e.target.reset();toast('Welcome to Verdant Living.');};document.querySelector('#searchButton').onclick=()=>{activeSpace='All';activeFilter='All';renderProducts();document.querySelector('#collection').scrollIntoView({behavior:'smooth'});toast('Browse the full collection below.');};renderProducts();renderCart();
